/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Csrf */
        post: operations["recoverCsrf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/botanical-identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listBotanicalIdentities"];
        put?: never;
        /** Create */
        post: operations["createBotanicalIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/botanical-identities/{botanical_identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getBotanicalIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/botanical-identities/{botanical_identity_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getBotanicalProfile"];
        /** Put */
        put: operations["putBotanicalProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geographic-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listGeographicPlaces"];
        put?: never;
        /** Create */
        post: operations["createGeographicPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geographic-places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getGeographicPlace"];
        /** Update */
        put: operations["updateGeographicPlace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geographic-places/{place_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate */
        post: operations["reactivateGeographicPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geographic-places/{place_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retireGeographicPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listLocations"];
        put?: never;
        /** Create */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getLocation"];
        /** Update */
        put: operations["updateLocation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate */
        post: operations["reactivateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retireLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seed-lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listSeedLots"];
        put?: never;
        /** Create */
        post: operations["createSeedLot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seed-lots/{seed_lot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getSeedLot"];
        /** Update */
        put: operations["updateSeedLot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sowings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listSowings"];
        put?: never;
        /** Create */
        post: operations["createSowing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sowings/{sowing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getSowing"];
        /** Update */
        put: operations["updateSowing"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["listSuppliers"];
        put?: never;
        /** Create */
        post: operations["createSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["getSupplier"];
        /** Update */
        put: operations["updateSupplier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate */
        post: operations["reactivateSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retireSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BotanicalIdentityCreate */
        BotanicalIdentityCreate: {
            /** Common Name */
            common_name?: string | null;
            /** Cultivar Name */
            cultivar_name?: string | null;
            /** Scientific Name */
            scientific_name: string;
        };
        /** BotanicalIdentityResponse */
        BotanicalIdentityResponse: {
            /** Common Name */
            common_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cultivar Name */
            cultivar_name: string | null;
            /** Display Label */
            display_label: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scientific Name */
            scientific_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BotanicalIdentitySummary */
        BotanicalIdentitySummary: {
            /** Display Label */
            display_label: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** BotanicalProfilePut */
        BotanicalProfilePut: {
            /** Cultivation */
            cultivation?: string | null;
            /** Description */
            description?: string | null;
            /** Origin Distribution */
            origin_distribution?: string | null;
            /** Uses */
            uses?: string | null;
            /** Warnings */
            warnings?: string | null;
        };
        /** BotanicalProfileResponse */
        BotanicalProfileResponse: {
            /**
             * Botanical Identity Id
             * Format: uuid
             */
            botanical_identity_id: string;
            /** Cultivation */
            cultivation: string | null;
            /** Description */
            description: string | null;
            /** Origin Distribution */
            origin_distribution: string | null;
            /** Uses */
            uses: string | null;
            /** Warnings */
            warnings: string | null;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** GeographicPlaceCreate */
        GeographicPlaceCreate: {
            /** Name */
            name: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
        };
        /** GeographicPlaceResponse */
        GeographicPlaceResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Path */
            display_path: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /**
             * Place Kind
             * @enum {string}
             */
            place_kind: "canonical" | "custom";
            /** Retired At */
            retired_at: string | null;
            /** Source Code */
            source_code: string | null;
            /** Source Code Type */
            source_code_type: string | null;
            /** Source Name */
            source_name: string | null;
            /** Source Version */
            source_version: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GeographicPlaceSummary */
        GeographicPlaceSummary: {
            /** Display Path */
            display_path: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** GeographicPlaceUpdate */
        GeographicPlaceUpdate: {
            /** Name */
            name: string;
            /**
             * Parent Id
             * Format: uuid
             */
            parent_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** LocationResponse */
        LocationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Path */
            display_path: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Retired At */
            retired_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LocationSummary */
        LocationSummary: {
            /** Display Path */
            display_path: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** LocationUpdate */
        LocationUpdate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login Name */
            login_name: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Status */
            status: string;
        };
        /** PartialDate */
        PartialDate: {
            /** Day */
            day?: number | null;
            /** Month */
            month?: number | null;
            precision: components["schemas"]["PartialDatePrecision"];
            /** Year */
            year: number;
        };
        /**
         * PartialDatePrecision
         * @enum {string}
         */
        PartialDatePrecision: "year" | "month" | "day";
        /** SeedLotCreate */
        SeedLotCreate: {
            acquisition_date?: components["schemas"]["PartialDate"] | null;
            /**
             * Botanical Identity Id
             * Format: uuid
             */
            botanical_identity_id: string;
            expected_viability_until?: components["schemas"]["PartialDate"] | null;
            harvest_date?: components["schemas"]["PartialDate"] | null;
            /** Label */
            label?: string | null;
            /** @default active */
            lifecycle: components["schemas"]["SeedLotLifecycle"];
            /** Location Id */
            location_id?: string | null;
            /** Material Provenance Place Id */
            material_provenance_place_id?: string | null;
            /** Notes */
            notes?: string | null;
            quantity?: components["schemas"]["SeedQuantity-Input"] | null;
            /** Source Detail */
            source_detail?: string | null;
            /** @default unknown */
            source_kind: components["schemas"]["SeedLotSourceKind"];
            /** Supplier Id */
            supplier_id?: string | null;
        };
        /**
         * SeedLotLifecycle
         * @enum {string}
         */
        SeedLotLifecycle: "active" | "exhausted" | "discarded" | "lost";
        /** SeedLotResponse */
        SeedLotResponse: {
            acquisition_date: components["schemas"]["PartialDate"] | null;
            botanical_identity: components["schemas"]["BotanicalIdentitySummary"];
            /**
             * Botanical Identity Id
             * Format: uuid
             */
            botanical_identity_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            expected_viability_until: components["schemas"]["PartialDate"] | null;
            harvest_date: components["schemas"]["PartialDate"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            lifecycle: components["schemas"]["SeedLotLifecycle"];
            location: components["schemas"]["LocationSummary"] | null;
            /** Location Id */
            location_id: string | null;
            material_provenance: components["schemas"]["GeographicPlaceSummary"] | null;
            /** Material Provenance Place Id */
            material_provenance_place_id: string | null;
            /** Notes */
            notes: string | null;
            quantity: components["schemas"]["SeedQuantity-Output"] | null;
            /** Source Detail */
            source_detail: string | null;
            source_kind: components["schemas"]["SeedLotSourceKind"];
            supplier: components["schemas"]["SupplierSummary"] | null;
            /** Supplier Id */
            supplier_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SeedLotSourceKind
         * @enum {string}
         */
        SeedLotSourceKind: "purchased" | "purchased_fruit" | "self_collected" | "collection_produced" | "gift_exchange" | "other" | "unknown";
        /** SeedLotUpdate */
        SeedLotUpdate: {
            acquisition_date?: components["schemas"]["PartialDate"] | null;
            /**
             * Botanical Identity Id
             * Format: uuid
             */
            botanical_identity_id: string;
            expected_viability_until?: components["schemas"]["PartialDate"] | null;
            harvest_date?: components["schemas"]["PartialDate"] | null;
            /** Label */
            label?: string | null;
            /** @default active */
            lifecycle: components["schemas"]["SeedLotLifecycle"];
            /** Location Id */
            location_id?: string | null;
            /** Material Provenance Place Id */
            material_provenance_place_id?: string | null;
            /** Notes */
            notes?: string | null;
            quantity?: components["schemas"]["SeedQuantity-Input"] | null;
            /** Source Detail */
            source_detail?: string | null;
            /** @default unknown */
            source_kind: components["schemas"]["SeedLotSourceKind"];
            /** Supplier Id */
            supplier_id?: string | null;
        };
        /** SeedQuantity */
        "SeedQuantity-Input": {
            /** Is Approximate */
            is_approximate: boolean;
            kind: components["schemas"]["SeedQuantityKind"];
            unit?: components["schemas"]["SeedWeightUnit"] | null;
            /** Value */
            value: number | string;
        };
        /** SeedQuantity */
        "SeedQuantity-Output": {
            /** Is Approximate */
            is_approximate: boolean;
            kind: components["schemas"]["SeedQuantityKind"];
            unit?: components["schemas"]["SeedWeightUnit"] | null;
            /**
             * Value
             * @description An exact non-negative decimal serialized as a JSON string.
             */
            value: string;
        };
        /**
         * SeedQuantityKind
         * @enum {string}
         */
        SeedQuantityKind: "seed_count" | "weight";
        /**
         * SeedWeightUnit
         * @enum {string}
         */
        SeedWeightUnit: "g" | "mg";
        /** SessionResponse */
        SessionResponse: {
            /** Display Name */
            display_name: string | null;
            /** Login Name */
            login_name: string;
            /** Owner */
            owner: boolean;
            /** User Id */
            user_id: string;
        };
        /** SowingCreate */
        SowingCreate: {
            /** Environment */
            environment?: string | null;
            /** Germinated Count */
            germinated_count?: number | null;
            /** Label */
            label?: string | null;
            /** @default active */
            lifecycle: components["schemas"]["SowingLifecycle"];
            /** Location Id */
            location_id?: string | null;
            /** Method Container */
            method_container?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pretreatment */
            pretreatment?: string | null;
            quantity?: components["schemas"]["SowingQuantity-Input"] | null;
            /**
             * Seed Lot Id
             * Format: uuid
             */
            seed_lot_id: string;
            sowing_date?: components["schemas"]["PartialDate"] | null;
            /** Substrate */
            substrate?: string | null;
            /** Temperature Max C */
            temperature_max_c?: number | string | null;
            /** Temperature Min C */
            temperature_min_c?: number | string | null;
        };
        /**
         * SowingLifecycle
         * @enum {string}
         */
        SowingLifecycle: "active" | "completed" | "failed" | "abandoned";
        /** SowingLocationSummary */
        SowingLocationSummary: {
            /** Display Path */
            display_path: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** SowingQuantity */
        "SowingQuantity-Input": {
            /** Is Approximate */
            is_approximate: boolean;
            kind: components["schemas"]["SeedQuantityKind"];
            unit?: components["schemas"]["SeedWeightUnit"] | null;
            /** Value */
            value: number | string;
        };
        /** SowingQuantity */
        "SowingQuantity-Output": {
            /** Is Approximate */
            is_approximate: boolean;
            kind: components["schemas"]["SeedQuantityKind"];
            unit?: components["schemas"]["SeedWeightUnit"] | null;
            /**
             * Value
             * @description An exact non-negative decimal serialized as a JSON string.
             */
            value: string;
        };
        /** SowingResponse */
        SowingResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Environment */
            environment: string | null;
            /** Germinated Count */
            germinated_count: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            lifecycle: components["schemas"]["SowingLifecycle"];
            location: components["schemas"]["SowingLocationSummary"] | null;
            /** Location Id */
            location_id: string | null;
            /** Method Container */
            method_container: string | null;
            /** Notes */
            notes: string | null;
            /** Pretreatment */
            pretreatment: string | null;
            quantity: components["schemas"]["SowingQuantity-Output"] | null;
            seed_lot: components["schemas"]["SowingSeedLotSummary"];
            /**
             * Seed Lot Id
             * Format: uuid
             */
            seed_lot_id: string;
            sowing_date: components["schemas"]["PartialDate"] | null;
            /** Substrate */
            substrate: string | null;
            /** Temperature Max C */
            temperature_max_c: string | null;
            /** Temperature Min C */
            temperature_min_c: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SowingSeedLotSummary */
        SowingSeedLotSummary: {
            /** Botanical Identity Display Label */
            botanical_identity_display_label: string;
            /**
             * Botanical Identity Id
             * Format: uuid
             */
            botanical_identity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            lifecycle: components["schemas"]["SeedLotLifecycle"];
        };
        /** SowingUpdate */
        SowingUpdate: {
            /** Environment */
            environment?: string | null;
            /** Germinated Count */
            germinated_count?: number | null;
            /** Label */
            label?: string | null;
            /** @default active */
            lifecycle: components["schemas"]["SowingLifecycle"];
            /** Location Id */
            location_id?: string | null;
            /** Method Container */
            method_container?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pretreatment */
            pretreatment?: string | null;
            quantity?: components["schemas"]["SowingQuantity-Input"] | null;
            /**
             * Seed Lot Id
             * Format: uuid
             */
            seed_lot_id: string;
            sowing_date?: components["schemas"]["PartialDate"] | null;
            /** Substrate */
            substrate?: string | null;
            /** Temperature Max C */
            temperature_max_c?: number | string | null;
            /** Temperature Min C */
            temperature_min_c?: number | string | null;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Email */
            email?: string | null;
            kind: components["schemas"]["SupplierKind"];
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
        };
        /**
         * SupplierKind
         * @enum {string}
         */
        SupplierKind: "seller" | "nursery" | "supermarket" | "person" | "exchange" | "other";
        /** SupplierResponse */
        SupplierResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SupplierKind"];
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Phone */
            phone: string | null;
            /** Retired At */
            retired_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /** SupplierSummary */
        SupplierSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Email */
            email?: string | null;
            kind: components["schemas"]["SupplierKind"];
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recoverCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    listBotanicalIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotanicalIdentityResponse"][];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBotanicalIdentity: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotanicalIdentityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description Canonical URL of the created BotanicalIdentity */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotanicalIdentityResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Botanical identity already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBotanicalIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                botanical_identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotanicalIdentityResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Botanical identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBotanicalProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                botanical_identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotanicalProfileResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identity or profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    putBotanicalProfile: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                botanical_identity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotanicalProfilePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotanicalProfileResponse"];
                };
            };
            /** @description Botanical profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Final section cleared; profile removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Botanical identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Profile content invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGeographicPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"][];
                };
            };
        };
    };
    createGeographicPlace: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeographicPlaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getGeographicPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateGeographicPlace: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeographicPlaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivateGeographicPlace: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retireGeographicPlace: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographicPlaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"][];
                };
            };
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivateLocation: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retireLocation: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listSeedLots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedLotResponse"][];
                };
            };
        };
    };
    createSeedLot: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedLotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedLotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSeedLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seed_lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedLotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateSeedLot: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                seed_lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedLotUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedLotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSowings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SowingResponse"][];
                };
            };
        };
    };
    createSowing: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SowingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SowingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSowing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sowing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SowingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateSowing: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                sowing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SowingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SowingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSuppliers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"][];
                };
            };
        };
    };
    createSupplier: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateSupplier: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivateSupplier: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retireSupplier: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
